export const HERO_STATUS = {
  ACTIVE: 'ACTIVE',
  SIDELINED: 'SIDELINED',
  DISGRACED: 'DISGRACED',
  EXILED: 'EXILED'
};

export const HERO_CONSTANTS = {
  HEAT_BASE: 2.4,
  GRIEVANCE_BASE: 1.6,
  // Unrest now acts as a magnifier (0..1) rather than a threshold gate.
  HEAT_DECAY_GOOD: 0.35,
  HEAT_DECAY_BAD: 0.1,
  GRIEVANCE_DECAY: 0.04,
  GRIEVANCE_BAKE_THRESHOLD: 60,
  GRIEVANCE_BAKE_RATE: 0.015,
  GRIEVANCE_BAKE_RELEASE: 0.35,
  POPULARITY_RISE_GOOD: 0.5,
  POPULARITY_FALL_BAD: 0.6,
  POPULARITY_CAP_FACTOR: 0.5,
  CHARGE_PER_CREDIT: 0.2, // 0.02 -> 0.2
  ABILITY_DEFAULT_CHARGE: 100,
  STATUS_CHARGE_MULTIPLIER: {
    ACTIVE: 1,
    SIDELINED: 0.6,
    DISGRACED: 0.3,
    EXILED: 0
  },
  AGGRAVATION_HEAT_DRIFT: 0.08,
  AGGRAVATION_GRIEVANCE_DRIFT: 0.12,
  LAW_HEAT_NEUTRAL: 12,
  LAW_GRIEVANCE_NEUTRAL: 8,
  LAW_HEAT_PRESSURE_SPAN: 40,
  LAW_GRIEVANCE_PRESSURE_SPAN: 35,
  LAW_UNREST_FROM_HEAT: 0.02,
  LAW_REJECT_FROM_GRIEVANCE: 0.016
};

export const HERO_RECRUIT_DELAY_RANGE = { min: 5, max: 25 };
export const HERO_RECRUIT_CHOICE_COUNT = 2;
